"""Add read_at column to messages table

Revision ID: 2643d37fd26d
Revises: 868c3cef9b0f
Create Date: 2025-08-31 22:21:33.995651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643d37fd26d'
down_revision = '868c3cef9b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_requested_at')
        batch_op.drop_column('verification_document_type')
        batch_op.drop_column('verification_document_photo')
        batch_op.drop_column('verification_document_number')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_requested')
        batch_op.drop_column('verification_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('verification_requested', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('verification_document_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('verification_document_photo', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('verification_document_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_requested_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
